version: '3.1'

services:
    
    web-server:
        image: webdev89/phpdebian
        restart: always
        container_name: php-memcached   
        ports:
          - 8920:80
        environment:
            DB_HOST: db
            DB_DB: mem
            DB_USER: user
            DB_PASS: user
            MEMCACHED: memcached
        volumes:
          - ./src/:/var/www/html
        depends_on:
          - db
        networks:
          - memcachedLinks
          
    memcached:
        image: memcached
        container_name: Memcached
        restart: always
        networks:
          - memcachedLinks
    
    db:
        image: mysql:5.7
        container_name: MysqlMemcached
        restart: always
        ports:
          - 8906:3306
        environment:
          MYSQL_DATABASE: mem
          MYSQL_USER: user 
          MYSQL_PASSWORD: user
          MYSQL_ROOT_PASSWORD: root
        volumes:
          - ./mysql_dump:/docker-entrypoint-initdb.d
          - MysqlMemcached:/var/lib/mysql
        networks:
          - memcachedLinks

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin_mem
        restart: always
        ports: 
          - 8927:80
        environment:
          PMA_HOST: db
        depends_on:
          - db
        networks:
          - memcachedLinks
          
networks:
  memcachedLinks:
    driver: bridge

volumes:
  MysqlMemcached: