version: '3.1'

services:
    
    web-server:
        image: webdev89/phpdebian
        restart: always
        container_name: php-memcached   
        ports:
          - 8920:80
        environment:
            DB_HOST: db
            DB_DB: mem
            DB_USER: user
            DB_PASS: user
            MEMCACHED_1: memcached-1
            MEMCACHED_2: memcached-2
            MEMCACHED_3: memcached-3
        volumes:
          - ./src/:/var/www/html
        depends_on:
          - db
        networks:
          - memcachedLinks
          
    memcached-1:
        image: memcached
        container_name: Memcached-1
        restart: always
        networks:
          - memcachedLinks
    memcached-2:
        image: memcached
        container_name: Memcached-2
        restart: always
        networks:
          - memcachedLinks
    memcached-3:
        image: memcached
        container_name: Memcached-3
        restart: always
        networks:
          - memcachedLinks
    
    db:
        image: mysql:5.7
        container_name: MysqlMemcached
        restart: always
        ports:
          - 8906:3306
        environment:
          MYSQL_DATABASE: mem
          MYSQL_USER: user 
          MYSQL_PASSWORD: user
          MYSQL_ROOT_PASSWORD: root
        volumes:
          - ./mysql_dump:/docker-entrypoint-initdb.d
          - MysqlMemcached:/var/lib/mysql
        networks:
          - memcachedLinks
          
    db-slave:
        image: mysql:5.7
        container_name: MysqlMemcachedSlave
        restart: always
        ports:
          - 8907:3306
        environment:
          MYSQL_USER: slave
          MYSQL_PASSWORD: slave
          MYSQL_ROOT_PASSWORD: root
        volumes:
          - MysqlSlave:/var/lib/mysql
        networks:
          - memcachedLinks
    
    db-slave-2:
        image: mysql:5.7
        container_name: MysqlMemcachedSlave2
        restart: always
        ports:
          - 8908:3306
        environment:
          MYSQL_USER: slave
          MYSQL_PASSWORD: slave
          MYSQL_ROOT_PASSWORD: root
        volumes:
          - MysqlSlave2:/var/lib/mysql
        networks:
          - memcachedLinks      

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin_mem
        restart: always
        ports: 
          - 8927:80
        environment:
          PMA_HOST: db
        depends_on:
          - db
        networks:
          - memcachedLinks
          
networks:
  memcachedLinks:
    driver: bridge

volumes:
  MysqlMemcached:
  MysqlSlave:
  MysqlSlave2: